apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfservice-cust-assist-qn
spec:
  selector:
    matchLabels:
      app: selfservice-cust-assist-qn
  template:
    metadata:
      labels:
        app: selfservice-cust-assist-qn
    spec:
      containers:
      - name: selfservice-cust-assist-qn
        image: quay.io/ibm/ai-on-power-genai-selfservice-cust-assist-qna:v0.0.1 
        ports:
        - name: selfsvc-http
          containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: selfservice-cust-assist-qn
spec:
  selector:
    app: selfservice-cust-assist-qn
  ports:
    - name: selfservice-cust-assist-qn
      protocol: TCP
      port: 8050
      targetPort: selfsvc-http
