apiVersion: v1
kind: Secret
metadata:
  name: huggingface-token
stringData:
  token: $HUGGING_FACE_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watsonx-ai-model-adapter
spec:
  selector:
    matchLabels:
      app: watsonx-ai-model-adapter
  template:
    metadata:
      labels:
        app: watsonx-ai-model-adapter
    spec:
      nodeSelector:
        kubernetes.io/hostname: p114worker04.b2s001.pbm.ihost.com
      containers:
      - name: watsonx-ai-model-adapter
        image: quay.io/ibm/ai-on-power-genai-watsonx-ai-model-adapter:v0.0.9
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
        - name: MODEL
          value: "$MODEL"
        resources:
          requests:
            memory: "100Gi"
            cpu: "47"
          limits:
            memory: "200Gi"
            cpu: "48"
        ports:
        - name: watsonx-http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: watsonx-ai-model-adapter
spec:
  selector:
    app: watsonx-ai-model-adapter
  ports:
    - name: watsonx-http
      protocol: TCP
      port: 8080
      targetPort: watsonx-http
